button styles
front-end-by-rimantas/35-grupe-portfolio-oxo pull request #42
Opened 2022-04-14 13:45 UTC by PauliusRa1987

Padariau stilius, kol kai kuriu button hover keistai vaiksto, nes jiems dar reikia ir visa stulpeli stumdyti..
Ir realiai teko hoveryje koreguoti padding nes backgroud turi uzeiti i border vieta.. tai paziurekit ten..
Beje pastebejau kad HERO sekcijoje button hover dalyje turi irgi balta borderi, kuris reaguoja kitaip nei kiti..
Gero ziurejimo :D

2022-04-14 16:41 UTC, neigiamasJonas requested changes
hey, atrodo, tai nice, tik kai kurie mygtukai uzhoverinus labai juda kazkaip, kiti graziai hoverinasi, tai nzn ar cia taip turi ar kazkas durniuoja?:) jei klystu - parashyk uzaprovinsiu : )

2022-04-14 16:52 UTC, TomUrin commented on css/components/button.css
> +    padding: 14px 39px;
Cia kur left ir right paddingas turetu buti tie patys 40px, nes kitaip truputi tekstas hoverio metu nuvaziuoja.

2022-04-14 16:54 UTC, TomUrin commented on css/components/button.css
> +    padding: 14px 40px;
Cia buvo toks jausmas, kad turejo buti borderis tiesiog nematomas kol nera hoverio ir delto nekeiciantis savo vizualios pozicijos, pabandziau prideti - border: 1px solid transparent; lygtai geriau atrodo.

2022-04-14 16:55 UTC, TomUrin requested changes
Palikau komentaru, del hero sekcijos mygtuko, kiti atrodo gerai.

2022-04-14 17:39 UTC, PauliusRa1987 commented
Padariau pakitimus, Aciu chebra uz patarimus, tikrai dabar geriau atrodo.
Prasau patikrinti ir duoti ziniu, jei kas ne taip ;)

2022-04-14 18:05 UTC, TomUrin approved these changes
Viskas veikia gerai.

2022-04-14 18:06 UTC, TomUrin commented on css/components/button.css
> +    padding: 14px 40px;
Dabar viskas ok 👍

2022-04-14 18:06 UTC, TomUrin commented
Kazkoks conflictas yra index.html

2022-04-14 19:15 UTC, neigiamasJonas approved these changes
yep, veikia : )

2022-04-14 19:19 UTC, neigiamasJonas approved these changes
sutaisiau konflikta, ten mazas buvo, nes abu toj pacioj sekcijos rasinejom, dabar all good turi but : )

2022-04-15 05:08 UTC, TomUrin approved these changes

2022-04-15 05:08 UTC, merged